version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app  # Descriptive name
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules  # Mount with cache option

# Improved Dockerfile with optimizations (replace placeholders)