apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
      - name: my-express-app
        image: 258e3e0a0fff
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URI
          valueFrom:
           secretKeyRef:
              name: mongo-db-uri
              key: DATABASE_URI
        resources:
          requests:
            cpu: 100m
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:  # Add readiness probe
          httpGet:
            path: /  # Replace with your application's health check path
            port: 3000  # Replace with your application's health check port (if different)
          initialDelaySeconds: 15  # Adjust delay before starting probe
          periodSeconds: 20 

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-uri
type: Opaque
stringData:
  # Replace with your actual connection string
  DATABASE_URI: mongodb://express-mongo-1:27017/hello
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-express-app
  minReplicas: 1  
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  
    - type: Resource
      resource:
        name: http_requests 
        target:
          type: AverageValue
          averageValue: "0.8"