version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URI=${DATABASE_URI}

volumes:
  mongo-data:
